version: '3.8'

services:
  core:
    container_name: core
    build:
      dockerfile: Dockerfile
      context: .
    command: make run
    depends_on:
      - redis
    environment:
      APP_PORT: '${CORE_PORT}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      LOG_LEVEL: '${LOG_LEVEL}'
      RIDER_API_KEY: '${RIDER_API_KEY}'
      CLIENT_API_KEY: '${CLIENT_API_KEY}'
      REDIS_LOCATION_KEY: '${REDIS_LOCATION_KEY}'
    ports:
      - "${CORE_PORT:-8080}:8080"
    volumes:
      - ./:/app

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      CACHE_SERVICE_PORT: '${REDIS_PORT}'
      CACHE_SERVICE_PASSWORD: '${REDIS_PASSWORD}'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - cache_volume:/data

volumes:
  cache_volume:
    driver: local
  db_volume:
    driver: local